# Generated by Django 2.1.3 on 2019-01-21 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='090', max_length=20, unique=True, verbose_name='phone number'),
            preserve_default=False,
        ),
    ]
