# Generated by Django 2.1.3 on 2019-04-09 20:48

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bvn',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True)),
        ),
    ]
