# Generated by Django 2.1.3 on 2018-11-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0002_auto_20181126_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('1', 'Approved'), ('2', 'Suspended'), ('0', 'Awaiting Approval')], default='0', max_length=50),
        ),
    ]
