# Generated by Django 2.1.3 on 2019-01-02 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cab.Route'),
        ),
    ]
