# Generated by Django 2.1.3 on 2019-01-02 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0005_auto_20190102_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Booking Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('1', 'SEARCHING FOR DRIVER'), ('2', 'WAITING FOR PICKUP'), ('3', 'IN PROGRESS'), ('4', 'COMPLETED')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
