# Generated by Django 2.1.3 on 2019-01-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0006_auto_20190102_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='billing_status',
            field=models.CharField(choices=[('0', 'UNPAID'), ('1', 'PAID')], default='0', max_length=2, verbose_name='Billing status'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Booking time'),
        ),
    ]
