# Generated by Django 2.1.3 on 2019-01-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0007_auto_20190102_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('1', 'SEARCHING FOR DRIVER'), ('2', 'WAITING FOR PICKUP'), ('3', 'IN PROGRESS'), ('4', 'COMPLETED'), ('5', 'CANCEL')], default='1', max_length=2),
        ),
    ]
