# Generated by Django 2.1.3 on 2019-02-05 21:53

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0008_auto_20190110_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
