# Generated by Django 2.1.3 on 2019-02-07 09:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0009_driver_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='socket_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
