# Generated by Django 2.1.3 on 2019-03-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0010_driver_socket_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('plate_no', models.CharField(max_length=15)),
                ('image', models.ImageField(default='cars/no-img.jpg', upload_to='cars/')),
                ('status', models.CharField(choices=[('1', 'Available'), ('0', 'Unavailable')], default='0', max_length=50)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
