# Generated by Django 2.1.3 on 2019-03-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0013_car_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(default='cars/no-img.jpg', upload_to='parks/'),
        ),
    ]
